/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChucNangCon;

import Form.DangNhap;
import Form.HeThong;
import Model.CTHoaDon;
import Model.HoaDon;
import Model.SanPhamBan;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class BaoCaoThongKe extends javax.swing.JFrame {

    /**
     * Creates new form BaoCaoThongKe
     */
    private final HoaDon hd=new HoaDon();
    private final SanPhamBan spb=new SanPhamBan();
    private final DefaultTableModel tableModel=new DefaultTableModel();
    public BaoCaoThongKe() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNam = new javax.swing.JTextField();
        cmbThang = new javax.swing.JComboBox<>();
        btnThongKe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongKe = new javax.swing.JTable();
        cmbHienThi = new javax.swing.JComboBox<>();
        cmbDanhMuc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblTong = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("BÁO CÁO THỐNG KÊ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 20, -1, 40));

        jLabel2.setText("Tháng:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 89, -1, -1));

        jLabel3.setText("Năm:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 89, -1, -1));
        getContentPane().add(txtNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 86, 72, -1));

        cmbThang.setBackground(new java.awt.Color(153, 204, 255));
        cmbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cmbThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 86, 50, -1));

        btnThongKe.setBackground(new java.awt.Color(255, 255, 204));
        btnThongKe.setIcon(new javax.swing.ImageIcon("D:\\Documents\\HK2(2022-2023)\\Java\\Anh\\thongke.png")); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        getContentPane().add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        tbThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tbThongKe);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 127, 769, 320));

        cmbHienThi.setBackground(new java.awt.Color(153, 204, 255));
        cmbHienThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Theo tháng năm" }));
        getContentPane().add(cmbHienThi, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 86, -1, -1));

        cmbDanhMuc.setBackground(new java.awt.Color(153, 204, 255));
        cmbDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hóa đơn", "Sản phẩm bán" }));
        getContentPane().add(cmbDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 86, 90, -1));

        jLabel4.setText("Tổng tiền:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 89, -1, -1));
        getContentPane().add(lblTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 86, 67, 23));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\HK2(2022-2023)\\Java\\Anh\\home.png")); // NOI18N
        jButton1.setText("Trang chủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Documents\\HK2(2022-2023)\\Java\\Anh\\nen3.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ShowData(int thang,int nam) throws SQLException{
        List<HoaDon> lst= hd.getData(thang,nam);
        try {
            for (HoaDon a : lst) {
                Object[] row={a.getMaHD(),a.getMaNV(),a.getNgayLap(),a.getThanhTien(),a.getMaKhach()};
                tableModel.addRow(row);
            }
            setTongTien();
        } catch (Exception e) {
            throw e;
        }
    }
    public void setTongTien()
    {
        int n=tableModel.getRowCount();
        float gia=0;
        float tong=0;
        for(int i=0;i<n;i++)
        {
            String str=tableModel.getValueAt(i, 3).toString();
            gia=Float.parseFloat(str);
            tong+=gia;
        }
        
        lblTong.setText(String.valueOf(tong));
    }
    public void setTongTien1()
    {
        int n=tableModel.getRowCount();
        float gia=0;
        float tong=0;
        for(int i=0;i<n;i++)
        {
            String str=tableModel.getValueAt(i, 4).toString();
            gia=Float.parseFloat(str);
            tong+=gia;
        }
        
        lblTong.setText(String.valueOf(tong));
    }
    public void ShowData1() throws SQLException{
        List<HoaDon> lst= hd.getData();
        try {
            for (HoaDon a : lst) {
                Object[] row={a.getMaHD(),a.getMaNV(),a.getNgayLap(),a.getThanhTien(),a.getMaKhach()};
                tableModel.addRow(row);
            }
            setTongTien();
        } catch (Exception e) {
            throw e;
        }
    }
    public void ShowData2() throws SQLException{
        List<SanPhamBan> lst= spb.getData();
        try {
            for (SanPhamBan a : lst) {
                Object[] row={a.getMaSach(),a.getTenSach(),a.getSoLuong(),a.getTongtien()};
                tableModel.addRow(row);
            }
            setTongTien1();
        } catch (Exception e) {
            throw e;
        }
    }
    public void ShowData3(int thang,int nam) throws SQLException{
        List<SanPhamBan> lst= spb.getData(thang,nam);
        try {
            for (SanPhamBan a : lst) {
                Object[] row={a.getMaSach(),a.getTenSach(),a.getNgayBan(),a.getSoLuong(),a.getTongtien()};
                tableModel.addRow(row);
            }
            setTongTien1();
        } catch (Exception e) {
            throw e;
        }
    }
     public void ClearData() throws SQLException{
        int n=tableModel.getRowCount()-1;
        for(int i=n;i>=0;i--)
            tableModel.removeRow(i);
    }
    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        String danhmuc=(String)cmbDanhMuc.getSelectedItem();
        String hienthi=(String)cmbHienThi.getSelectedItem();
        try {
            if(hienthi.equalsIgnoreCase("Tất cả") )
            {
                if(danhmuc.equalsIgnoreCase("Hóa đơn"))
                {
                    String[] colsName={"Mã Hóa Đơn","Mã Nhân Viên","Ngày Lập","Thành Tiền","Mã Khách"};
                    tableModel.setColumnIdentifiers(colsName);
                    tbThongKe.setModel(tableModel);
                    try {
                        ClearData();
                        ShowData1();
                    } catch (SQLException ex) {
                        Logger.getLogger(BaoCaoThongKe.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(danhmuc.equalsIgnoreCase("Sản phẩm bán"))
                {
                    String[] colsName={"Mã Sách","Tên Sách","Số lượng","Tổng Tiền"};
                    tableModel.setColumnIdentifiers(colsName);
                    tbThongKe.setModel(tableModel);
                    try {
                        ClearData();
                        ShowData2();
                    } catch (SQLException ex) {
                        Logger.getLogger(BaoCaoThongKe.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                   
            }
            else
            {
                if(!txtNam.getText().isEmpty())
                {
                    int nam=Integer.parseInt(txtNam.getText());
                    int thang=Integer.parseInt((String)cmbThang.getSelectedItem());
                    if(danhmuc.equalsIgnoreCase("Hóa đơn"))
                    {
                        String[] colsName={"Mã Hóa Đơn","Mã Nhân Viên","Ngày Lập","Thành Tiền","Mã Khách"};
                        tableModel.setColumnIdentifiers(colsName);
                        tbThongKe.setModel(tableModel);
                        try {
                            ClearData();
                            ShowData(thang,nam);
                        } catch (SQLException ex) {
                            Logger.getLogger(BaoCaoThongKe.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else if(danhmuc.equalsIgnoreCase("Sản phẩm bán"))
                    {
                        String[] colsName={"Mã Sách","Tên Sách","Ngày Bán","Số lượng","Tổng Tiền"};
                        tableModel.setColumnIdentifiers(colsName);
                        tbThongKe.setModel(tableModel);
                        try {
                            ClearData();
                            ShowData3(thang,nam);
                        } catch (SQLException ex) {
                            Logger.getLogger(BaoCaoThongKe.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }   
                else
                {
                    JOptionPane.showMessageDialog(this, "Năm không được để trống");
                }
            }
            
        } catch (NumberFormatException e) {
            
        }
        
        
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HeThong frm=new HeThong();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCaoThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe;
    private javax.swing.JComboBox<String> cmbDanhMuc;
    private javax.swing.JComboBox<String> cmbHienThi;
    private javax.swing.JComboBox<String> cmbThang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTong;
    private javax.swing.JTable tbThongKe;
    private javax.swing.JTextField txtNam;
    // End of variables declaration//GEN-END:variables
}
