/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import ChucNangCon.BaoCaoThongKe;
import ChucNangCon.QuanLyBanHang;
import ChucNangCon.QuanLyNhanVien;
import ChucNangCon.QuanLySach;

/**
 *
 * @author ADMIN
 */
public class HeThong extends javax.swing.JFrame {

    /**
     * Creates new form HeThong
     */
    public HeThong() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQLK = new javax.swing.JButton();
        btnQLNV = new javax.swing.JButton();
        btnQLSP = new javax.swing.JButton();
        btnQLBH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLK.setBackground(new java.awt.Color(245, 108, 49));
        btnQLK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLK.setText("BÁO CÁO-THỐNG KÊ");
        btnQLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLK, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 150, 31));

        btnQLNV.setBackground(new java.awt.Color(245, 108, 49));
        btnQLNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLNV.setText("QUẢN LÝ NHÂN VIÊN");
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, 35));

        btnQLSP.setBackground(new java.awt.Color(245, 108, 49));
        btnQLSP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLSP.setText("QUẢN LÝ SÁCH");
        btnQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSPActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 150, 31));

        btnQLBH.setBackground(new java.awt.Color(245, 108, 49));
        btnQLBH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLBH.setText("QUẢN LÝ BÁN HÀNG");
        btnQLBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLBHActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLBH, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 150, 34));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chọn chức năng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, -1, -1));

        jButton1.setBackground(new java.awt.Color(245, 108, 49));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("ĐĂNG XUẤT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 150, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\HK2(2022-2023)\\Java\\Anh\\chucnang.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        // TODO add your handling code here:
        QuanLyNhanVien frm=new QuanLyNhanVien();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSPActionPerformed
        // TODO add your handling code here:
        QuanLySach frm=new QuanLySach();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLSPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DangNhap frm=new DangNhap();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnQLBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLBHActionPerformed
        // TODO add your handling code here:
        QuanLyBanHang frm=new QuanLyBanHang();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLBHActionPerformed

    private void btnQLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKActionPerformed
        // TODO add your handling code here:
        BaoCaoThongKe frm=new BaoCaoThongKe();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLKActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLBH;
    private javax.swing.JButton btnQLK;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
